#!/usr/bin/env python3
"""Convert our proven open-refund targets into a ForgottenETH contribution.

ForgottenETH (github.com/q84c6tsm95-create/forgotten-eth) is the canonical stuck-ETH
registry. A protocol contribution is two files:
  1. an entry in `data/protocols.json`  {key,name,contract,balance_source,category,balance_file[,multi_step]}
  2. `data/balances/<key>_eth_balances.json`  {contract, balance_source, contract_eth_balance,
       total_eth_in_balances, addresses_with_balance, coverage_pct, scan_date, description,
       balances:{addr->eth}}  -- the per-holder claimable amounts (EOA-only, self-claimable).
The index_shards / table_meta / total.json are GENERATED by the maintainer's pipeline -- a
contributor never hand-edits them (verified against merged PRs #2/#10/#12).

This reads our `docs/targets/owners_<ourkey>.json` (from enumerate_owners.py / storage reads)
and emits both files per target into `contrib/forgotten-eth/`, filtered to SELF-CLAIMABLE EOAs
(the maintainer's standard): contracts excluded, and EXCHANGE/SERVICE hot wallets excluded
(deposits credited to an exchange's omnibus address can't be claimed by the end user). No RPC.

Usage: python3 scripts/make_feth_contribution.py
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCAN_DATE = "2026-06-10 00:00:00 UTC"  # snapshot ~ fork block 25_270_000

# NOT self-claimable: exchange / service hot wallets that deposited to the ICO on behalf of users
# (the refund pays the exchange's omnibus address, not the original contributor). Identified by
# Etherscan name tags + exchange-scale tx nonces (>=300k); the maintainer rejects these.
EXCLUDE = {
    "0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98",  # Bittrex (nonce 11.5M)
    "0x32be343b94f860124dc4fee278fdcbd38c102d88",  # Poloniex (nonce 1.5M)
    "0x267be1c1d684f78cb4f6a176c4911b741e4ffdc0",  # service (nonce 5.2M)
    "0xd24400ae8bfebb18ca49be86258a3c749cf46853",  # service (nonce 4.5M)
    "0x7ed1e469fcb3ee19c0366d829e291451be638e59",  # service (nonce 508k)
    "0x5baeac0a0417a05733884852aa068b706967e790",  # service (nonce 300k)
}

# our owners_<ourkey>.json  ->  ForgottenETH protocol metadata. `desc` is mechanism-only;
# the self-claimable contributor count is appended dynamically (kept accurate after filtering).
CONTRIB = [
    {"ourkey": "digipulse", "fethkey": "digipulse_token_sale",
     "name": "DigiPulse (DGT) Token Sale", "category": "ico", "method": "refundEther()",
     "desc": "Failed Aug-2017 DGT ICO (raised ~1,920 ETH vs an 8,000 ETH minimum). finalise() "
             "latched icoFailed=true, opening refundEther(), which returns each contributor their "
             "own ethBalanceOf deposit. Self-paying, not front-runnable; owner cannot drain "
             "(withdrawFundsToOwner needs icoFulfilled, false forever)."},
    {"ourkey": "directcrypt", "fethkey": "directcrypt_presale",
     "name": "DirectCrypt Token Presale", "category": "ico", "method": "refund()",
     "desc": "Failed 2017 DRCT presale (soft cap never reached). refund() returns each contributor "
             "their own deposited[] balance while softCapReached==false. Owner cannot drain "
             "(withdraw needs softCap); owner can halt() refunds (reversible pause, not a drain) -- "
             "refunds confirmed open on a fork."},
    {"ourkey": "qcotoken", "fethkey": "qcotoken_ico",
     "name": "QCOToken (Quantum1Net) Sale", "category": "ico", "method": "requestRefund()",
     "desc": "Quantum1Net QCO sale ended in the Aborted state (terminal). requestRefund() returns "
             "each contributor their own ethPossibleRefunds[] deposit. Owner drain path needs the "
             "Operational state, unreachable from Aborted."},
    {"ourkey": "hodlethereum", "fethkey": "hodl_ethereum",
     "name": "hodlEthereum", "category": "other", "method": "party()",
     "desc": "2017 time-locked savings vault. Each depositor's ETH was credited to hodlers[] and "
             "became reclaimable after partyTime (1596067200 = 2020-07-30, long past) via party(). "
             "No owner/admin/pause/sweep -- fully immutable. "
             "(Distinct contract from the existing just_hodl_it entry.)"},
    {"ourkey": "blocklancer", "fethkey": "blocklancer_ico",
     "name": "Blocklancer (LNC) Token Sale", "category": "ico", "method": "refund()",
     "desc": "Failed 2017 LNC ICO (minimum cap not reached). refund() returns each contributor "
             "their own balancesEther[] deposit (public getter EtherBalanceOf). master's only "
             "ETH-out, finalize(), reverts for this failed raise (proven on a fork) -- cannot drain."},
    {"ourkey": "ztcrowdsale", "fethkey": "ztcrowdsale",
     "name": "ZTCrowdsale (ZeroTraffic)", "category": "ico", "method": "endCrowdsale() then refund()",
     "multi_step": True,
     "desc": "Failed 2017 ZeroTraffic crowdsale (raised ~21 ETH vs a 20,000 ETH minimum). "
             "Permissionless 2-step: anyone calls endCrowdsale() (now past end, no owner gate) to "
             "open the Ended stage, then each contributor refund()s their own balances[] deposit. "
             "withdraw() needs raised>=min (never) -- company cannot drain. Per-owner amounts read "
             "from private storage slot 23; pre-ICO deposits were auto-forwarded out and excluded."},
]


def main():
    out_bal = os.path.join(ROOT, "contrib", "forgotten-eth", "balances")
    os.makedirs(out_bal, exist_ok=True)
    protocols_entries = []
    summary = []
    for c in CONTRIB:
        owners = json.load(open(os.path.join(ROOT, "docs", "targets", f"owners_{c['ourkey']}.json")))
        contract = owners["contract"].lower()
        live = round(owners["live_balance_eth"], 8)
        # Self-claimable EOAs only: drop contracts AND exchange/service hot wallets.
        eoa = [o for o in owners["unclaimed"]
               if o.get("eoa") and o["address"].lower() not in EXCLUDE]
        eoa.sort(key=lambda o: -o["eth"])
        balances = {o["address"].lower(): round(o["eth"], 8) for o in eoa}
        # Clamp the published total so it can never exceed what the contract actually holds
        # (per-entry 8-dp rounding can otherwise sum a few gwei past the true balance).
        total = min(round(sum(balances.values()), 8), live)
        coverage = round(total / live * 100, 2) if live else 0.0

        desc = c["desc"] + f" {len(balances)} self-claimable contributors are unclaimed " \
                           f"(contracts and exchange-deposit addresses excluded)."
        bal_file = f"{c['fethkey']}_eth_balances.json"
        bal_obj = {
            "contract": contract,
            "balance_source": "token",   # precomputed per-holder (matches ahoolee/jincor/agrotech/luckchemy)
            "contract_eth_balance": live,
            "total_eth_in_balances": total,
            "addresses_with_balance": len(balances),
            "coverage_pct": coverage,
            "scan_date": SCAN_DATE,
            "description": desc,
            "balances": balances,
        }
        json.dump(bal_obj, open(os.path.join(out_bal, bal_file), "w"), indent=2)

        entry = {"key": c["fethkey"], "name": c["name"], "contract": contract,
                 "balance_source": "token", "category": c["category"], "balance_file": bal_file}
        if c.get("multi_step"):
            entry["multi_step"] = True
        protocols_entries.append(entry)
        summary.append((c["name"], len(balances), total, coverage, c["method"]))

    cdir = os.path.join(ROOT, "contrib", "forgotten-eth")
    json.dump(protocols_entries, open(os.path.join(cdir, "protocols_entries.json"), "w"), indent=2)

    print("ForgottenETH contribution prepared -> contrib/forgotten-eth/")
    print(f"{'protocol':30} {'owners':>6} {'ETH':>10} {'cov%':>6}  recovery")
    print("-" * 78)
    tot_eth = tot_own = 0
    for name, n, eth, cov, method in summary:
        print(f"{name:30} {n:>6} {eth:>10.4f} {cov:>6.1f}  {method}")
        tot_eth += eth; tot_own += n
    print("-" * 78)
    print(f"{'TOTAL':30} {tot_own:>6} {tot_eth:>10.4f}")
    print(f"\nfiles: contrib/forgotten-eth/balances/*.json (6) + protocols_entries.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
